### ISSUE TITLE
Font Case

### ISSUE THREAD

**Issue by cdemetriadis** [design-ops/stylable-swiftui#18] opened 2020-04-30 13:05 UTC
We need to be able to change the font case based on the theme.

We need to have three styles:

**Normal:** Use the current text casing
**Uppercase:** Force convert all letters to UPPERCASE
**Lowercase:** Force convert all letters to lowercase

**Comment by kerrmarin** [comment] 2020-04-30 13:36
This is a duplicate of #10

**Closed as completed by kerrmarin** 2020-04-30 13:36 UTC
